- cs414-f19-001-Blueberries.iml
- pom.xml
- src/client/.gitignore
- src/client/README.md
- src/client/package-lock.json
- src/client/package.json
- src/client/src/App.js
- src/client/src/App.test.js
- src/client/src/index.js
- src/server/main/GameApi.java
- src/server/main/Player.java
Add initial setup for Maven and React so that react is script-ready to run on localhost:3000
> Add necessary initial setup along with a dummy api example

- src/client/public/index.html
TO RUN THIS PROGRAM:
copy the repository
run the java server
(when in the "client" folder on a command line) run "npm start"
> Add html file containing root div

- JSONfiles/Players.json
- TIP.md
- TestFiles/TestPlayers.json
- pom.xml
- src/server/Test/com/cs414/blueberries/TestGlobalData.java
- src/server/Test/com/cs414/blueberries/TestPlayer.java
- src/server/main/com/cs414/blueberries/GameApi.java
- src/server/main/com/cs414/blueberries/GlobalData.java
- src/server/main/com/cs414/blueberries/Player.java
> Server now loads from Players.json on startup. TIP specifies Players.json

- src/client/src/App.js
- src/client/src/Login.js
- src/client/src/Login.test.js
- src/client/src/Register.js
- src/client/src/Register.test.js
Added basic login and register page, along with the render tests for them. Closes #13
> Added login and register page.

- JSONfiles/Players.json
- TIP.md
- src/server/Test/com/cs414/blueberries/TestGlobalData.java
- src/server/Test/com/cs414/blueberries/TestPlayer.java
- src/server/main/com/cs414/blueberries/GameApi.java
- src/server/main/com/cs414/blueberries/GlobalData.java
- src/server/main/com/cs414/blueberries/Player.java
> Login api created, TIP.md updated to correspond

- JSONfiles/Games.json
- TIP.md
- src/server/main/com/cs414/blueberries/Game.java
- src/server/main/com/cs414/blueberries/GameApi.java
- src/server/main/com/cs414/blueberries/Player.java
Pay close attention to the TIP.md to see how to use the new endpoints.
> Add ability to send and receive invites as well as retrieve all games

- src/server/main/com/cs414/blueberries/Bishop.java
- src/server/main/com/cs414/blueberries/King.java
- src/server/main/com/cs414/blueberries/Pawn.java
> update pawn bishop and king

- pom.xml
- src/client/package-lock.json
- src/client/package.json
- src/client/src/App.js
- src/client/src/History.js
- src/client/src/Home.js
- src/client/src/Login.js
- src/client/src/PrivateRoute.js
- src/client/src/Register.js
- src/server/main/com/cs414/blueberries/GameApi.java
Fix linking for login, register and home by adding react router dom package. Change GameApi to work with CORS, and change login API to return a fail if not pass.
> Fix linking

- src/client/src/App.js
- src/client/src/Home.js
Removed route props from login, and home.
> Remove route props

- src/client/src/App.js
- src/client/src/Home.js
- src/client/src/Login.js
- src/client/src/PrivateRoute.js
- src/client/src/Register.js
- Redid login request on login page
- Added props to non private pages
- Used localStorage to pass userID
- Added ID display to homepage
- Added logout link to homepage
- Change homepage rendering display
> Add ID to home page

- DevGuide.md
> Add developer's guide

- JSONfiles/Players.json
- Sprints/Sprint 2/Traceability Link Matrix.md
- src/client/src/Register.js
- src/server/Test/com/cs414/blueberries/TestPlayer.java
- src/server/main/com/cs414/blueberries/Player.java
Updated traceability link matrix
> Link matrix

- src/client/src/Board.js
- src/client/src/Home.js
- src/client/src/Square.js
- src/client/src/pieces.css
- src/server/main/com/cs414/blueberries/Board.java
Will display any game (pending, active, or sent) that is attached to an individual user at their home screen.
> Add initial display of board objects

- src/server/Test/com/cs414/blueberries/TestKing.java
- src/server/main/com/cs414/blueberries/King.java
* Fix king move, king can't move into check, and fix move for black pieces. 
* Checkmate is working for no possible moves for king, a piece of same color can capture a piece to get out of check.
* Checkmate for a piece blocking a checkmate is NOT working.
> King class

- src/client/package-lock.json
- src/client/package.json
- src/client/src/Cookies.js
- src/client/src/GameHistory.js
- src/client/src/Home.js
- src/client/src/Login.js
- src/server/main/com/cs414/blueberries/Game.java
- src/server/main/com/cs414/blueberries/GameApi.java
user can now view their own game history. 
things to note:
- Server side game class now has Winner, startTime, endTime and finished variables. endTime and Winner will need to be set by whoever is doing end game detection
> Gamehistroy

- src/client/src/Home.js
- src/client/src/Invite.js
* Added invite screen in form of modal
* Added accept invite button to pending invites
* Added send invite form
* Changed Home page layout by putting all buttons onto one row
* Changed Home page layout by removing some heading/Text
* Change Home page by adding game ID to the games
* Fix url Addr bug in Invite page
> Invite screen

- src/client/src/App.js
- src/client/src/Home.js
- src/client/src/Unregister.js
- src/server/main/com/cs414/blueberries/GameApi.java
- src/server/main/com/cs414/blueberries/Player.java
> gorgenzola v2 electric boogaloo

- src/client/src/Invite.js
- src/server/main/com/cs414/blueberries/GameApi.java
* Fix invite page reject function
* Added API end point for reject
> Add reject functionality

- src/client/src/Home.js
- src/client/src/Rules.js
> Added rules

- src/client/src/Home.js
- src/server/main/com/cs414/blueberries/GameApi.java
* Added API end point for forfeit
* Added button and request for forfeit on client side
I had forfeit working before I committed, but I now I some how broke all the API requests. If someone could check if this branch to see if it works.
> Added forfeit
